version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: .build/php/Dockerfile
        container_name: villa-fratelli-php
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - .:/var/www/

    nginx:
        image: nginx:stable-alpine
        container_name: villa-fratelli-nginx
        restart: unless-stopped
        depends_on:
            - php
        working_dir: /var/www/
        ports:
            - "8144:80"
        volumes:
            - .:/var/www/
            - .build/nginx/nginx-default.conf:/etc/nginx/conf.d/default.conf:cached